name: Nix

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix-check:
    name: Nix checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ github.sha }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-
            nix-${{ runner.os }}-${{ runner.arch }}-

      - name: Check flake
        run: nix flake check --print-build-logs

  apk:
    name: Build APK
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ github.sha }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-
            nix-${{ runner.os }}-${{ runner.arch }}-

      - name: Build APK
        run: nix build .#apk --print-build-logs

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: opennutritracker-develop-debug
          path: result/app-develop-debug.apk
          retention-days: 14
          if-no-files-found: error
